package com.lianlianpay.global.ew.openapi.model.account.exchanges;

import lombok.Data;

import java.io.Serializable;

/**
 * @author huyl
 * @since 2024/12/5
 */
@Data
public class ConversionCreateReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Conversion requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * sell_currency
     * required
     * string
     * Sell currency, the currency that the client sells (in 3-letter ISO-4217 format).
     */
    private String sellCurrency;

    /**
     * sell_amount
     * string
     * Amount in sell_currency that the client sells. Must be specified if buy_amount is not specified.
     *
     * Amount, main currency unit, rounded up to 2 decimal places.
     */
    private String sellAmount;

    /**
     * buy_currency
     * required
     * string
     * Buy currency, the currency that the client buys (in 3-letter ISO-4217 format).
     */
    private String buyCurrency;

    /**
     * buy_amount
     * string
     * Amount in buy_currency that the client buys. Must be specified if sell_amount is not specified.
     *
     * Amount, main currency unit, rounded up to 2 decimal places.
     */
    private String buyAmount;

    /**
     * rate_id
     * required
     * string
     * The rate_id will be used to execute the conversion.
     */
    private String rateId;
}
