package com.lianlianpay.global.ew.openapi.model.account.service;

import lombok.Data;

import java.io.Serializable;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/5
 */
@Data
public class RemittanceCreateReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Payout requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string <= 64 characters
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * pay_currency
     * string
     * (in three-letter ISO 4217 format).
     * USD
     */
    private String payCurrency;

    /**
     * send_currency
     * string
     * (in three-letter ISO 4217 format).
     * CNY
     */
    private String sendCurrency;

    /**
     * send_amount
     * string
     * Send amount and pay amount must specify one
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String sendAmount;

    /**
     * pay_amount
     * string
     * Send amount and pay amount must specify one
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String payAmount;

    /**
     * purpose
     * required
     * string
     * It indicates the source/usage of funds in a transaction.
     * TOURISM_FX_SETTLE:Foreign exchange settlement for tourism services
     * INSURANCE_PAYOUTS:Insurance payouts (except investment insurance)
     * PATENT_ROYALTY:Patent royalty
     * SERVICE_REVENUE:Revenue from legal, accounting, consulting and public relations services
     * OTHER:Service for other purposes
     * WAGE_AND_FAMILY:Wage & family support
     * INVESTMENT: Overseas investment income
     * RED_ENVELOPE:Red envelope (Hongbao) for celebration, etc
     */
    private String purpose;

    /**
     * payer_info
     * object (PayerInfo)
     * It is present only when the developer's entity is PSP/MSO. This Payer’s Information is in use of verification or anti money laundering.
     */
    private PayerInfo payerInfo;

    /**
     * payee_name
     * required
     * string <= 30 characters
     * Chinese spelling letters (PIN YIN) are used if Chinese names are submitted. The first letter of the first name is capitalized. In Pinyin, the last name is before the first name. In English, the last name is after the first name, separated by spaces.
     */
    private String payeeName;

    /**
     * payee_account
     * required
     * string <= 19 characters
     * It can be filled with payee's PAN.
     */
    private String payeeAccount;

    /**
     * reference
     * string <= 50 characters
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * additional_info
     * object (Map)
     * Set of key-value pairs that you can attach the business information according to Lianlian Global's requirements.
     */
    private Map<String, String> additionalInfo;
}
