package com.lianlianpay.global.ew.openapi.model.account.query;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author huyl
 * @since 2024/12/5
 */
@Data
public class TransactionDetailRes implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * id
     * string
     * Unique ID created by the LianLian Global.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * amount
     * string
     * Transaction amount, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * currency
     * string
     * Three-letter ISO 4217 currency code.
     */
    private String currency;

    /**
     * name
     * string
     * Name of the counterparty.
     */
    private String name;

    /**
     * type
     * string
     * Enum: "PAYOUT" "RECEIPT" "CONVERSION" "WITHDRAWAL" "ADD_FUNDS" "RECEIVING" "REFUND" "CARD_PAYOUT" "PROMO_COMMISSION" "STANDING_PAYMENT"
     * Transaction type.
     */
    private String type;

    /**
     * user_id
     * string
     * Unique identifier of the user.
     */
    private String userId;

    /**
     * status
     * string
     * Enum: "PROCESSING" "COMPLETED" "CANCELED" "REFUNDING" "REFUNDED" "FAILED"
     * The transaction status.
     */
    private String status;

    /**
     * create_time
     * long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
