package com.lianlianpay.global.ew.openapi.model.supporting;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * Bank Account Verify Request
 * @author huyl
 * @since 2025/4/1
 */
@Data
public class BankAccountVerifyReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * bank_account_number
     * required
     * string <= 64 characters
     * Bank account number.
     */
    private String bankAccountNumber;

    /**
     * bank_account_name
     * required
     * string <= 128 characters
     * Bank account name.
     */
    private String bankAccountName;

    /**
     * cnaps_code
     * required
     * string <= 64 characters
     * CNAPS code.
     */
    private String cnapsCode;

    /**
     * bank_code
     * string <= 64 characters
     * Bank code.
     */
    private String bankCode;

    /**
     * additional_info
     * Array of objects (Item)
     * extra info
     */
    private List<AdditionalInfo> additionalInfo;
}
