package com.lianlianpay.global.ew.openapi.model.supporting;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author huyl
 * @since 2025/4/29
 */
@Data
public class TransactionDocumentPageReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * business_type
     * required
     * string
     * Enum: "ECOMMERCE" "GOODS_TRADE"
     * The type of business.
     */
    private String businessType;

    /**
     * start_time
     * long
     * Transaction object creation period start time. Measured in millisecond since the Unix epoch.
     */
    private Date startTime;

    /**
     * end_time
     * long
     * Transaction object creation period end time. Measured in millisecond since the Unix epoch.
     */
    private Date endTime;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request.
     */
    private String requestId;

    /**
     * owner_type
     * string
     * Enum: "BENEFICIARY" "PAYER"
     * The party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region) Enum: "BENEFICIARY" When the recipient receives funds in a currency that is a controlled currency of a currency-controlled country. "PAYER" When the currency ofpayment by the payer is a controlled currency of a currency-controlled country.
     * Required if business_type = GOODS_TRADE
     */
    private String ownerType;

    /**
     * owner_id
     * string
     * The id of the party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region)
     * Required if business_type = GOODS_TRADE
     */
    private String ownerId;

    /**
     * purpose
     * string
     * Enum: "PAYOUT" "RECEIVING" "WITHDRAW"
     * Purpose of the transaction document.
     * Required if business_type = GOODS_TRADE
     */
    private String purpose;

    /**
     * status
     * string
     * Enum: "PROCESSING" "SUCCEEDED" "FAILED"
     * The status of transaction documents
     */
    private String status;

    /**
     * page
     * required
     * integer
     * The query page number.
     */
    private Integer page;

    /**
     * page_size
     * required
     * integer
     * A maximum of 100 data items can be displayed on a page.
     */
    private Integer pageSize;
}
