package com.lianlianpay.global.ew.openapi.model.supporting;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author huyl
 * @since 2025/2/7
 */
@Data
public class TransactionDocumentCreateReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Might be order ID or contract number.
     */
    private String requestId;

    /**
     * merchant_client_id
     * required
     * string <= 128 characters
     * Merchant ID as known by the client platform.
     */
    private String merchantClientId;

    /**
     * Number of contract
     * Required if business_type = GOODS_TRADE
     */
    private String contractNo;

    /**
     * business_type
     * required
     * string
     * Enum: "ECOMMERCE" "GOODS_TRADE"
     * The type of business.
     */
    private String businessType;

    /**
     * original_order_type
     * string
     * Enum: "GOODS" "SERVICES"
     * Order type.
     * Required if business_type=ECOMMERCE
     */
    private String originalOrderType;

    /**
     * purpose
     * string
     * Enum: "PAYOUT" "RECEIVING" "WITHDRAW"
     * Purpose of the transaction document.
     * Required if business_type = GOODS_TRADE
     */
    private String purpose;

    /**
     * owner_type
     * string
     * Enum: "BENEFICIARY" "PAYER"
     * The party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region) Enum: "BENEFICIARY" When the recipient receives funds in a currency that is a controlled currency of a currency-controlled country. "PAYER" When the currency of payment by the payer is a controlled currency of a currency-controlled country.
     * Required if business_type=GOODS_TRADE.
     */
    private String ownerType;

    /**
     * owner_id
     * string
     * The id of the party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region)
     * Required if business_type=GOODS_TRADE.
     */
    private String ownerId;

    /**
     * Enum: "REGULAR" "CUSTOMS" "WITHOUT_SETTLE"
     * The template of transaction document.
     * REGULAR: Ordinary foreign exchange settlement with a declaration code of 122030.
     * CUSTOMS: Customs-declared foreign exchange settlement with a customs declaration and declaration code is 121010
     * WITHOUT_SETTLE: No foreign exchange settlement needed
     */
    private String template;

    /**
     * The unique identifier of the transaction document
     */
    private String transactionDocumentId;

    /**
     * counterparty_details
     * required
     * object (CounterpartyDetails)
     * Counterparty details
     */
    private TransactionDocumentCounterparty counterpartyDetails;

    /**
     * trade_time
     * long
     * Creation time for this trade. Measured in milliseconds since the Unix epoch. It's a long type number.
     * Required if business_type=ECOMMERCE.
     */
    private Date tradeTime;

    /**
     * trade_currency
     * required
     * string
     * Currency of trade (in three-letter ISO 4217 format).
     */
    private String tradeCurrency;

    /**
     * trade_amount
     * required
     * string
     * The amount of trade, main currency unit, rounded up to 2 decimal places.
     */
    private String tradeAmount;

    /**
     * business_details
     * object (BusinessDetails)
     * Business details
     */
    private TransactionDocumentBusinessDetails businessDetails;


    /**
     * memo
     * string
     * memo
     * Required if business_type ="ECOMMERCE"
     */
    private String memo;
}
