package com.lianlianpay.global.ew.openapi.model.supporting;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * @author huyl
 * @since 2025/4/29
 */
@Data
public class TransactionDocumentUpdateRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Conversion requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * transaction_document_id
     * string
     * The unique identifier of the transaction document
     */
    private String transactionDocumentId;

    /**
     * create_time
     * long
     * The creation time of transaction documents.
     */
    private Date createTime;

    /**
     * status
     * string
     * Enum: "DENIED" "PROCESSING" "SUCCEEDED" "FAILED"
     * The status of transaction documents
     */
    private String status;

    /**
     * failure_code
     * string
     * Failure code Might return if status = "DENIED" or "FAILED"
     */
    private String failureCode;

    /**
     * failure_reason
     * string
     * Failure details Might return if status = "DENIED" or "FAILED"
     */
    private String failureReason;

    /**
     * result
     * boolean
     * Result of update TRUE / FALSE
     */
    private Boolean result;
}
