package com.lianlianpay.global.ew.openapi.model.supporting;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2025/2/7
 */
@Data
public class TransactionDocumentCreateReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Might be order ID or contract number.
     */
    private String requestId;

    /**
     * merchant_client_id
     * required
     * string <= 128 characters
     * Merchant ID as known by the client platform.
     */
    private String merchantClientId;

    /**
     * business_type
     * required
     * string
     * Enum: "ECOMMERCE" "GOODS_TRADE"
     * The type of business.
     */
    private String businessType;

    /**
     * original_order_type
     * string
     * Enum: "GOODS" "SERVICES"
     * Order type.
     * Required if business_type=ECOMMERCE
     */
    private String originalOrderType;

    /**
     * purpose
     * string
     * Enum: "PAYOUT" "RECEIVING" "WITHDRAW"
     * Purpose of the transaction document.
     * Required if business_type = GOODS_TRADE
     */
    private String purpose;

    /**
     * owner_type
     * string
     * Enum: "BENEFICIARY" "PAYER"
     * The party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region) Enum: "BENEFICIARY" When the recipient receives funds in a currency that is a controlled currency of a currency-controlled country. "PAYER" When the currency of payment by the payer is a controlled currency of a currency-controlled country.
     * Required if business_type=GOODS_TRADE.
     */
    private String ownerType;

    /**
     * owner_id
     * string
     * The id of the party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region)
     * Required if business_type=GOODS_TRADE.
     */
    private String ownerId;

    /**
     * counterparty_details
     * required
     * object (CounterpartyDetails)
     * Counterparty details
     */
    private TransactionDocumentCounterparty counterpartyDetails;

    /**
     * trade_time
     * long
     * Creation time for this trade. Measured in milliseconds since the Unix epoch. It's a long type number.
     * Required if business_type=ECOMMERCE.
     */
    private Date tradeTime;

    /**
     * trade_currency
     * required
     * string
     * Currency of trade (in three-letter ISO 4217 format).
     */
    private String tradeCurrency;

    /**
     * trade_amount
     * required
     * string
     * The amount of trade, main currency unit, rounded up to 2 decimal places.
     */
    private String tradeAmount;

    /**
     * settlement_flag
     * boolean
     * Enum: "TRUE" "FALSE"
     * Whether or not to settle into CNY
     * Required if business_type=GOODS_TRADE.
     */
    private Boolean settlementFlag;

    /**
     * declaration_method
     * string
     * Enum: "121010" "122030"
     * The method of declaration.
     * Required if sellerment_flag = TRUE, choose from:
     *
     * 121010 (General Trade)
     * 122030 (ECommerce Trade)
     */
    private String declarationMethod;

    /**
     * business_details
     * object (BusinessDetails)
     * Business details
     */
    private TransactionDocumentBusiness businessDetails;

    /**
     * attachments
     * Array of objects (Attachment)
     * Attachments
     */
    private List<TransactionDocumentAttachment> attachments;

    /**
     * customs_declaration
     * object (CustomsDeclaration)
     * Customs declaration information
     * Required if business_type = "GOODS_TRADE"and declaration_method=121010
     */
    private TransactionDocumentCustomsDeclaration customsDeclaration;

    /**
     * memo
     * string
     * memo
     * Required if business_type ="ECOMMERCE"
     */
    private String memo;
}
