package com.lianlianpay.global.ew.openapi.model.supporting;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2025/4/29
 */
@Data
public class TransactionDocumentCreateRes implements Serializable {

    private static final long serialVersionUID = 1L;


    /**
     * The idempotent value generated by the client must be unique on each request. Conversion requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Merchant ID as known by the client platform.
     */
    private String merchantClientId;

    /**
     * Enum: "ECOMMERCE" "GOODS_TRADE"
     * The type of business.
     */
    private String businessType;

    /**
     * Enum: "GOODS" "SERVICES"
     * Order type.
     * Required if business_type=ECOMMERCE
     */
    private String originalOrderType;

    /**
     * Purpose of the transaction document.
     * Required if business_type = GOODS_TRADE
     */
    private String purpose;

    /**
     * Enum: "BENEFICIARY" "PAYER"
     * The party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region) Enum: "BENEFICIARY" When the recipient receives funds in a currency that is a controlled currency of a currency-controlled country. "PAYER" When the currency of payment by the payer is a controlled currency of a currency-controlled country.
     */
    private String ownerType;

    /**
     * The id of the party who own this transaction document. Must be transferred if the currency of the parties to the transaction involves a currency controlled by a currency controlled country. (e.g. when payment is made in the currency of CNY in the CN region)
     */
    private String ownerId;

    /**
     * Business details
     */
    private TransactionDocumentCounterparty counterpartyDetails;

    /**
     * Creation time for this trade. Measured in milliseconds since the Unix epoch. It's a long type number.
     * Required if business_type=ECOMMERCE.
     */
    private Date tradeTime;

    /**
     * Currency of trade (in three-letter ISO 4217 format).
     */
    private String tradeCurrency;

    /**
     * The amount of trade, main currency unit, rounded up to 2 decimal places.
     */
    private String tradeAmount;

    /**
     * Enum: "TRUE" "FALSE"
     * Whether or not to settle into CNY
     * Required if business_type=GOODS_TRADE.
     */
    private Boolean settlementFlag;

    /**
     * Enum: "121010" "122030"
     * The method of declaration.
     * Required if sellerment_flag = TRUE, choose from:
     *
     * 121010 (General Trade)
     * 122030 (ECommerce Trade)
     */
    private String declarationMethod;

    /**
     * Business details
     */
    private TransactionDocumentBusiness businessDetails;

    /**
     * Attachments
     */
    private List<TransactionDocumentAttachment> attachments;

    /**
     * Customs declaration information
     * Required if business_type = "GOODS_TRADE"and declaration_method=121010
     */
    private TransactionDocumentCustomsDeclaration customsDeclaration;

    /**
     * memo
     * Required if business_type ="ECOMMERCE"
     */
    private String memo;

    /**
     * The unique identifier of the transaction document
     */
    private String transactionDocumentId;

    /**
     * The creation time of transaction documents.
     */
    private Date createTime;

    /**
     * Enum: "PROCESSING" "SUCCEEDED" "FAILED"
     * The status of transaction documents
     */
    private String status;

    /**
     * Failure code Might return if status = "FAILED"
     */
    private String failureCode;

    /**
     * Failure details Might return if status = "FAILED"
     */
    private String failureReason;
}
