package com.lianlianpay.global.ew.openapi.model.account.payment;

import lombok.Data;

import java.io.Serializable;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class MandateCreateRes implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * The idempotent value generated by the client must be unique on each request. Consent requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * The Mandate URL for payer to pay on the Dashboard.
     */
    private String consentUrl;

    /**
     * The URL where the payer is redirected after he or she approves the Mandate.
     */
    private String returnUrl;

    /**
     * Value: "PAYMENT_AGREEMENT"
     * Signing Mandate type.
     */
    private String consentType;

    /**
     * Merchant ID as known by the client platform.
     */
    private String merchantClientId;

    /**
     * Merchant name as known by the client platform.
     */
    private String merchantClientName;

    /**
     * Customer info.
     */
    private CustomerInfo customer;

    /**
     * MERCHANT CUSTOMER.
     */
    private String triggeredBy;

    /**
     * Structured field names and values used to define the business information.
     */
    private Map<String, String> additionalInfo;
}
