package com.lianlianpay.global.ew.openapi.model.account.payment;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class MandateDetailRes implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * id
     * string
     * Unique identifier of the mandate.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Consent requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String accountId;

    /**
     * Value: "PAYMENT_AGREEMENT"
     * Signing mandate type.
     */
    private String consentType;

    /**
     * Enum: "PENDING" "ACTIVE" "CANCELED" "EXPIRED"
     * The payout status.
     */
    private String status;

    /**
     * Customer info.
     */
    private CustomerInfo customer;

    /**
     * Structured field names and values used to define the business information.
     */
    private Map<String, String> additionalInfo;

    /**
     * The object expires time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date expiryTime;

    /**
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
