package com.lianlianpay.global.ew.openapi.model.account.payment;

import lombok.Data;

import java.io.Serializable;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class MandateCreateReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Mandate requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * return_url
     * required
     * string
     * The URL where the payer is redirected after he or she approves the Mandate.
     */
    private String returnUrl;

    /**
     * consent_type
     * required
     * string
     * Value: "PAYMENT_AGREEMENT"
     * Signing consent type.
     */
    private String consentType;

    /**
     * customer
     * required
     * object (CustomerInfo)
     * Customer info.
     */
    private CustomerInfo customer;

    /**
     * additional_info
     * object (Map)
     * Structured field names and values used to define the business information.
     * <br/>
     * Filed value. If the key name is region, the value must be US, SG, HK, GB.
     */
    private Map<String, String> additionalInfo;
}
