package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class Payout2AppCreateReq implements Serializable {


    private static final long serialVersionUID = 1L;

    /**
     * string <br/>
     * The idempotent value generated by the client must be unique on each request. Payout requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * string <br/>
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * string <br/>
     * When exchange is required, the exchange rate ID can be obtained through [Create a LockFX Quote]. If left blank, the system will automatically complete the exchange.
     */
    private String rateId;

    /**
     * string <br/>
     * The actual currency of payment by the payer (in three-letter ISO 4217 format).
     */
    private String payCurrency;

    /**
     * string <br/>
     * Currency of payment to Contact (in three-letter ISO 4217 format).
     */
    private String sendCurrency;

    /**
     * string <br/>
     * Send amount and pay amount must specify one
     *
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String sendAmount;

    /**
     * string <br/>
     * Send amount and pay amount must specify one
     *
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String payAmount;

    /**
     * string <br/>
     * The ID of File Folder object.
     */
    private String fileFolderId;

    /**
     * string <br/>
     * This is the postscript information visible to the payee.
     */
    private String purpose;

    /**
     * string <br/>
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * Array of objects (Item)
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * string <br/>
     * APP ID as known by the client platform.
     */
    private String appClientId;
}
