package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class PayoutCreateReq implements Serializable {


    /**
     * Unique identifier of payee.
     * One and only one of the account Id, payee Id and merchant client Id must be provided.
     */
    private String payeeId;

    /**
     * Unique identifier of payer.
     */
    private String payerId;

    /**
     * One and only one of the account Id, payee Id and merchant client Id must be provided.
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String accountId;

    /**
     * One and only one of the account Id, payee Id and merchant client Id must be provided.
     *
     * Merchant ID as known by the client platform. Must be specified if payee_id is not specified.
     */
    private String payeeMerchantClientId;

    /**
     * The idempotent value generated by the client must be unique on each request.
     * payout requests with the same request_id will be rejected. The parameter contains a maximum of 128 characters.
     */
    private String requestId;

    /**
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * Beneficiary information
     */
    private BankAccountConnectReq beneficiary;

    /**
     * purpose of payout
     */
    private String purpose;

    /**
     * This parameter is required when exchange is required
     */
    private String rateId;

    /**
     * The actual currency of payment by the payer (in three-letter ISO 4217 format).
     */
    private String payCurrency;

    /**
     * Currency of payment to payee (in three-letter ISO 4217 format).
     */
    private String sendCurrency;

    /**
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String sendAmount;

    /**
     * Send amount and pay amount must specify one
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String payAmount;

    /**
     * Unique identification of required materials
     */
    private String fileFolderId;

    /**
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian Global's requirements.
     */
    private List<AdditionalInfo> additionalInfo;
}
