package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class RefundCreateReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * The idempotent value generated by the client must be unique on each request. Payout requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Business Order ID.
     * One and only one of the receipt order id, and request payment Id must be provided.
     */
    private String businessOrderId;

    /**
     * Unique identifier for the Receipt Object ID.
     * One and only one of the receipt order id, and request payment Id must be provided.
     */
    private String receiptOrderId;

    /**
     * Unique identifier for the Request payment Object ID.
     * One and only one of the receipt order id, and request payment Id must be provided.
     */
    private String requestPaymentId;

    /**
     * Currency of payment to Contact (in three-letter ISO 4217 format).
     */
    private String sendCurrency;

    /**
     * Send amount and pay amount must specify one
     */
    private String sendAmount;

    /**
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian Global's requirements.
     */
    private List<AdditionalInfo> additionalInfo;


}
