package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import com.lianlianpay.global.ew.openapi.model.common.FeeInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class RefundDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * id
     * String
     * Unique identifier of the refund.
     */
    private String id;

    /**
     * request_id
     * String
     * The idempotent value generated by the client must be unique on each request. Payout requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * String
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * receipt_order_id
     * String
     * Unique identifier for the Receipt Object ID.
     */
    private String receiptOrderId;

    /**
     * request_payment_id
     * String
     * Unique identifier for the Request payment Object ID.
     */
    private String requestPaymentId;

    /**
     * pay_currency
     * String
     * The currency actually paid by the payer (in three-letter ISO 4217 format).
     */
    private String payCurrency;

    /**
     * pay_amount
     * String
     * The amount actually paid by the payer, main currency unit, rounded up to 2 decimal places.
     */
    private String payAmount;

    /**
     * send_currency
     * String
     * Currency of payment to account (in three-letter ISO 4217 format).
     */
    private String sendCurrency;

    /**
     * send_amount
     * String
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String sendAmount;

    /**
     * fee
     * Object
     */
    private FeeInfo fee;

    /**
     * failure_code
     * String
     * This field occurs when an error occurs during payment.
     */
    private String failureCode;

    /**
     * failure_reason
     * String
     * This field occurs when an error occurs during payment.
     */
    private String failureReason;

    /**
     * status
     * String
     * Enum: "PROCESSING" "FAILED" "CANCELLED" "REFUNDING" "REFUNDED" "COMPLETED"
     * The payout status.
     */
    private String status;

    /**
     * reference
     * String
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * additional_info
     * Array of objects (Item)
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * create_time
     * Long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
