package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class RequestPaymentCreateReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * string <br/>
     * The idempotent value generated by the client must be unique on each request. Requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * string <br/>
     * One and only one of the payer account Id, payer Id, mandate Id must be provided.
     * <p>
     * Unique identifier for the Network Account Object.
     */
    private String payerId;

    /**
     * string <br/>
     * One and only one of the payer account Id, payer Id, mandate Id must be provided.
     * <p>
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String payerAccountId;

    /**
     * string <br/>
     * One and only one of the payer account Id, payer Id, mandate Id must be provided.
     * <p>
     * Unique identifier for the Mandate Object.
     */
    private String consentId;

    /**
     * string <br/>
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * string <br/>
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * * string <= 128 characters
     * Default values.<br/>
     * MERCHANDISE_TRADE <br/>
     * LOGISTICS_FEES <br/>
     * ADVERTISEMENT_FEES <br/>
     * E-COMMERCE_COLLECTION <br/>
     * COMMISSIONS_ON_TRANSACTIONS <br/>
     * WAGES_SALARY <br/>
     * COPYRIGHT_SALES <br/>
     * TAX_PAYMENT <br/>
     * TECHNICAL_SERVICE <br/>
     * If the send currency is CNY or purpose, please select the following enumeration values. <br/>
     * MERCHANDISE_TRADE <br/>
     * LOGISTICS_FEES <br/>
     * ADVERTISEMENT_FEES <br/>
     * E-COMMERCE_COLLECTION <br/>
     * COMMISSIONS_ON_TRANSACTIONS <br/>
     * WAGES_SALARY <br/>
     * If the send currency is THB VND BRL or purpose, please select the following enumeration values.<br/>
     * EXPORTED_GOODS <br/>
     * SERVICE_CHARGES <br/>
     * SALARY_PAYMENT
     */
    private String purpose;

    /**
     * string<br/>
     * The ID of File Folder object.
     */
    private String fileFolderId;

    /**
     * string <= 128 characters
     * This is the postscript information visible to the payer.
     */
    private String reference;

    /**
     * long <br/>
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch.
     */
    private Date expireTime;

    /**
     * Array of objects (Item) <br/>
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

}
