package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class RequestPaymentUrlRes implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * The idempotent value generated by the client must be unique on each request. Requests with the same request_id will be return last Request Payment URL if exists. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * Default values.
     * MERCHANDISE_TRADE
     * LOGISTICS_FEES
     * ADVERTISEMENT_FEES
     * E-COMMERCE_COLLECTION
     * COMMISSIONS_ON_TRANSACTIONS
     * WAGES_SALARY
     * COPYRIGHT_SALES
     * TAX_PAYMENT
     * TECHNICAL_SERVICE
     * If the send currency is CNY or purpose, please select the following enumeration values.
     * MERCHANDISE_TRADE
     * LOGISTICS_FEES
     * ADVERTISEMENT_FEES
     * E-COMMERCE_COLLECTION
     * COMMISSIONS_ON_TRANSACTIONS
     * WAGES_SALARY
     * If the send currency is THB VND BRL or purpose, please select the following enumeration values.
     * EXPORTED_GOODS
     * SERVICE_CHARGES
     * SALARY_PAYMENT
     * */
    private String purpose;

    /**
     * This is the postscript information visible to the payer.
     */
    private String reference;

    /**
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date expireTime;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * The URL where the payer is redirected after he or she approves the Request Payment.
     */
    private String returnUrl;

    /**
     * The Request Payment URL for payer to pay on the Dashboard.
     */
    private String requestPaymentUrl;
}
