package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class RequestPaymentDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * string <br/>
     * Unique ID created by the LianLian Global.
     */
    private String id;

    /**
     * string <br/>
     * The idempotent value generated by the client must be unique on each request. Requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * string <br/>
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * string <br/>
     * Unique identifier of the User.
     */
    private String userId;

    /**
     * string <br/>
     * Unique identifier for the Network Account Object.
     */
    private String payerId;

    /**
     * string <br/>
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String payerAccountId;

    /**
     * string <br/>
     * Payer name.
     */
    private String payerName;

    /**
     * string <money> <br/>
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * string <br/>
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * string <br/>
     * Purpose of Request Payment.
     */
    private String purpose;

    /**
     * string <br/>
     * The ID of File Folder object.
     */
    private String fileFolderId;

    /**
     * string <br/>
     * This is the postscript information visible to the payer.
     */
    private String reference;

    /**
     * long <br/>
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch.
     */
    private Date expireTime;

    /**
     * Array of objects (Item) <br/>
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * string <br/>
     * The Request Payment status.
     */
    private String status;

    /**
     * string <br/>
     * The Request Payment settlement status.
     */
    private String settlementStatus;

    /**
     * string <money> <br/>
     * The amount to settle, main currency unit, rounded up to 2 decimal places.
     */
    private String settlementAmount;

    /**
     * string <br/>
     * The currency to settle (in three-letter ISO 4217 format).
     */
    private String settlementCurrency;

    /**
     * string <money> <br/>
     * The fee to settle, main currency unit, rounded up to 2 decimal places.
     */
    private String settlementFee;
}
