package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import com.lianlianpay.global.ew.openapi.model.common.FeeInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class WithdrawDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * id
     * string
     * Unique identifier for the Withdraw Object ID.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Withdraw requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * beneficiary_id
     * string
     * Unique identifier for the Beneficiary Object ID.
     */
    private String beneficiaryId;

    /**
     * conversion
     * object (ConversionInfo)
     */
    private ConversionInfo conversion;

    /**
     * withdraw_currency
     * string
     * The currency actually paid by the payer (in three-letter ISO 4217 format).
     */
    private String withdrawCurrency;

    /**
     * withdraw_amount
     * string
     * The amount actually paid by the payer, main currency unit, rounded up to 2 decimal places.
     */
    private String withdrawAmount;

    /**
     * send_currency
     * string
     * Currency of payment to account (in three-letter ISO 4217 format).
     */
    private String sendCurrency;

    /**
     * send_amount
     * string
     * Amount paid to payee, main currency unit, rounded up to 2 decimal places.
     */
    private String sendAmount;

    /**
     * fee
     * object
     */
    private FeeInfo fee;

    /**
     * refund_currency
     * string
     * Return the funds to the payer's currency (in three-letter ISO 4217 format).
     */
    private String refundCurrency;

    /**
     * refund_amount
     * string
     * Return the funds to the payer's amount, main currency unit, rounded up to 2 decimal places.
     */
    private String refundAmount;

    /**
     * failure_code
     * string
     * This field occurs when an error occurs during withdraw.
     */
    private String failureCode;

    /**
     * failure_reason
     * string
     * This field occurs when an error occurs during withdraw.
     */
    private String failureReason;

    /**
     * status
     * string
     * Enum: "PROCESSING" "FAILED" "CANCELLED" "REFUNDING" "REFUNDED" "COMPLETED"
     * The withdrawal status.
     */
    private String status;

    /**
     * reference
     * string
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * additional_info
     * Array of objects (Item)
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * create_time
     * long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
