package com.lianlianpay.global.ew.openapi.model.account.payment;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import com.lianlianpay.global.ew.openapi.model.supporting.RelationTransactionDocument;
import lombok.Data;

import java.io.Serializable;
import java.util.List;

/**
 * @author huyl
 * @since 2024/12/3
 */
@Data
public class WithdrawCreateReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * The idempotent value generated by the client must be unique on each request. Withdraw requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Unique identifier for the Beneficiary Object ID.
     */
    private String beneficiaryId;

    /**
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * The currency actually paid by the payer (in three-letter ISO 4217 format).
     */
    private String withdrawCurrency;

    /**
     * The amount actually paid by the payer, main currency unit, rounded up to 2 decimal places.
     */
    private String withdrawAmount;

    /**
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * This parameter is required when exchange is required
     */
    private String rateId;

    /**
     * Enum: REGULAR, CUSTOMS，WITHOUT_SETTLE
     * The type of transaction document.
     */
    private String transactionDocumentType;

    /**
     * The transaction documents related to the withdrawal.
     */
    private List<RelationTransactionDocument> transactionDocumentList;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;
}
