package com.lianlianpay.global.ew.openapi.model.account.accounts;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;

/**
 * @author huyl
 * @since 2024/10/24
 */
@Data
public class AccountAuthorizeRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * authorization_code
     * string
     * The authorization code generated by LLG. It is used to exchange tokens. The authorization code expires in 30 seconds and becomes invalid once an access token is exchanged.
     */
    private String authorizationCode;
}
