package com.lianlianpay.global.ew.openapi.model.account.platform;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class SplitRes implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Unique identifier of the settle.
     */
    private String id;

    /**
     * prev request id.
     */
    private String prevRequestId;

    /**
     * The idempotent value generated by the client must be unique on each request. Account Settle requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * Unique identifier for the Account Object ID.
     */
    private String accountId;

    /**
     * Currency of account settle to Beneficiary (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * Amount paid to Beneficiary account, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * The bank reference field refers to the reference attached by the pay-in when sending the deposit to LLG. LLG uses this field to match funds received with the deposit splits you have created.
     */
    private String bankReference;

    /**
     * The funds split status.
     */
    private String status;

    /**
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;

    /**
     * Structured field names and values used to define the business information.
     */
    private Map<String, String> additionalInfo;
}
