package com.lianlianpay.global.ew.openapi.model.account.platform;

import lombok.Data;

import java.io.Serializable;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class SplitReleaseReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * request_id
     * required
     * string <= 64 characters
     * The idempotent value generated by the client must be unique on each request. Account Request requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * prev_request_id
     * required
     * string <= 64 characters
     * Request ID of the split original order.
     */
    private String prevRequestId;

    /**
     * business_order_id
     * string <= 64 characters
     * External associated order number, which may be order number or payment order number .
     */
    private String businessOrderId;

    /**
     * amount
     * required
     * string
     * Amount , main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * currency
     * required
     * string
     * Currency (in three-letter ISO 4217 format).
     */
    private String currency;

}
