package com.lianlianpay.global.ew.openapi.model.account.platform;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class SplitDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * id
     * string
     * Unique identifier of the settle.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Account Settle requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * account_id
     * string
     * Unique identifier for the Account Object ID.
     */
    private String accountId;

    /**
     * currency
     * string
     * Currency of account settle to Beneficiary (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * amount
     * string
     * Amount paid to Beneficiary account, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * released_amount
     * string
     * Amount already released, main currency unit, rounded up to 2 decimal places.
     */
    private String releasedAmount;

    /**
     * refunded_amount
     * string
     * Amount already refunded, main currency unit, rounded up to 2 decimal places.
     */
    private String refundedAmount;

    /**
     * bank_reference
     * string
     * The bank reference field refers to the reference attached by the pay-in when sending the deposit to LLG. LLG uses this field to match funds received with the deposit splits you have created.
     */
    private String bankReference;

    /**
     * split_categorize
     * string
     */
    private String splitCategorize;

    /**
     * status
     * string
     * Enum: "WAIT_DEPOSIT" "VERIFIED" "SETTLING" "COMPLETED"
     * The funds split status.
     */
    private String status;

    /**
     * create_time
     * long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;

    /**
     * additional_info
     * object (Map)
     * Structured field names and values used to define the business information.
     */
    private Map<String, String> additionalInfo;
}
