package com.lianlianpay.global.ew.openapi.model.account.platform;

import lombok.Data;

import java.io.Serializable;
import java.util.Map;

/**
 * @author huyl
 * @since 2024/12/4
 */
@Data
public class SplitCreateReq implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * request_id
     * required
     * string <= 64 characters
     * The idempotent value generated by the client must be unique on each request. Account Request requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string <= 64 characters
     * External associated order number, which may be order number or payment order number .
     */
    private String businessOrderId;

    /**
     * account_id
     * required
     * string
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String accountId;

    /**
     * currency
     * required
     * string
     * Currency of account settle to Beneficiary (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * amount
     * required
     * string
     * Amount paid to Beneficiary account, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * bank_reference
     * required
     * string <= 64 characters
     * The bank reference field refers to the reference attached by the pay-in when sending the deposit to LLG. LLG uses this field to match funds received with the deposit splits you have created.
     */
    private String bankReference;

    /**
     * split_categorize
     * string <= 64 characters
     */
    private String splitCategorize;

    /**
     * additional_info
     * object (Map)
     * Structured field names and values used to define the business information.
     */
    private Map<String, String> additionalInfo;
}
