package com.lianlianpay.global.ew.openapi.model.acceptance.payment.online;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/11/26
 */
@Data
public class ConsentDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * id
     * string
     * Unique identifier of the consent.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Consent requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * account_id
     * string
     * Account ID. Once this new account is created, it will be connected to your account and becomes the key value you communicate with LLG for any activities in the future.
     */
    private String accountId;

    /**
     * consent_type
     * string
     * Value: "PAYMENT_AGREEMENT"
     * Signing consent type.
     */
    private String consentType;

    /**
     * status
     * string
     * Enum: "PENDING" "ACTIVE" "CANCELED" "EXPIRED"
     * The payout status.
     */
    private String status;

    /**
     * customer
     * object (CustomerInfo)
     * Customer info.
     */
    private CustomerInfo customer;

    /**
     * additional_info
     * object (Map)
     * Structured field names and values used to define the business information.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * expiry_time
     * long
     * The object expires time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date expiryTime;

    /**
     * create_time
     * long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
