package com.lianlianpay.global.ew.openapi.model.acceptance.payment.online;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;

/**
 *
 * @author huyl
 * @since 2024/11/26
 */
@Data
public class ConsentCreateReq implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * request_id
     * required
     * string
     * The idempotent value generated by the client must be unique on each request. Consent requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * return_url
     * required
     * string
     * The URL where the payer is redirected after he or she approves the Consent.
     */
    private String returnUrl;

    /**
     * consent_type
     * required
     * string
     * Value: "PAYMENT_AGREEMENT"
     * Signing consent type.
     */
    private String consentType;

    /**
     * customer
     * required
     * object (CustomerInfo)
     * Customer info.
     */
    private CustomerInfo customer;

    /**
     * additional_info
     * object (Map)
     * Structured field names and values used to define the business information.
     */
    private AdditionalInfo additionalInfo;
}
