package com.lianlianpay.global.ew.openapi.model.acceptance.payment.online;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/11/25
 */
@Data
public class PaymentDetailRes implements Serializable {


    private static final long serialVersionUID = -1L;


    /**
     * id
     * string
     *
     * Unique ID created by the LianLian Global.
     */
    private String id;

    /**
     * request_id
     * required
     *
     * The idempotent value generated by the client must be unique on each request. Requests with the same request_id will be return last Request Payment URL if exists. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * consent_id
     * required
     *
     * Unique identifier for the Consent Object.
     */
    private String consentId;

    /**
     * amount
     * required
     *
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * currency
     * required
     *
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * payment_method
     * required
     *
     * Value: "Pay with LianLian"
     * Pay with LianLian.
     */
    private String paymentMethod;

    /**
     * customer
     * required
     *
     * CustomerInfo
     */
    private CustomerInfo customer;

    /**
     * orders
     * required
     *
     * Array of objects (OrderInfo)
     * Order infos.
     */
    private List<OrderInfo> orders;

    /**
     * expiry_time
     * long
     *
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date expiryTime;

    /**
     * additional_info
     * object (Map)
     *
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * pay_success_time
     * The object pay success time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date paySuccessTime;

    /**
     * create_time
     * long
     *
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;

    /**
     * Enum: "PROCESSING" "SUCCEEDED" "CANCELED" "EXPIRED" "FAILED"
     * The Request Payment status.
     */
    private String paymentStatus;
}
