package com.lianlianpay.global.ew.openapi.model.acceptance.payment.online;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;
import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/10/18
 */
@Data
public class PaymentRequestDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * The idempotent value generated by the client must be unique on each request. Requests with the same request_id will be return last Request Payment URL if exists. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * The amount to collect, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * The currency to collect (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * Value: "Pay with LianLian"
     * Pay with LianLian.
     */
    private String paymentMethod;

    /**
     * Customer information.
     */
    private CustomerInfo customer;

    /**
     * Order information.
     */
    private List<OrderInfo> orders;

    /**
     * Expire time for this Request Payment. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date expiryTime;

    /**
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * string
     * The URL where the payer is redirected after he or she approves the Request Payment.
     */
    private String returnUrl;

    /**
     * The Request Payment URL for payer to pay on the Dashboard.
     */
    private String paymentRequestUrl;

    /**
     * Enum: "PROCESSING" "SUCCEEDED" "CANCELED" "EXPIRED" "FAILED"
     * The Request Payment status.
     */
    private String paymentStatus;
}