package com.lianlianpay.global.ew.openapi.model.acceptance.payment.online;

import com.lianlianpay.global.ew.openapi.model.common.AdditionalInfo;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

/**
 * @author huyl
 * @since 2024/11/25
 */
@Data
public class RefundDetailRes implements Serializable {

    private static final long serialVersionUID = -1L;

    /**
     * id
     * string
     * Unique identifier of the refund.
     */
    private String id;

    /**
     * request_id
     * string
     * The idempotent value generated by the client must be unique on each request. Payout requests with the same request_id will be rejected. The parameter contains a maximum of 64 characters.
     */
    private String requestId;

    /**
     * business_order_id
     * string
     * Business Order ID.
     */
    private String businessOrderId;

    /**
     * payment_request_id
     * string
     * Unique identifier for the Payment request id Object payment_request_id.
     */
    private String paymentRequestId;

    /**
     * currency
     * string
     * The currency actually paid by the payer (in three-letter ISO 4217 format).
     */
    private String currency;

    /**
     * amount
     * string
     * The amount actually paid by the payer, main currency unit, rounded up to 2 decimal places.
     */
    private String amount;

    /**
     * failure_code
     * string
     * This field occurs when an error occurs during payment.
     */
    private String failureCode;

    /**
     * failure_reason
     * string
     * This field occurs when an error occurs during payment.
     */
    private String failureReason;

    /**
     * status
     * string
     * Enum: "PROCESSING" "FAILED" "EXPIRED" "COMPLETED"
     * The payout status.
     */
    private String status;

    /**
     * reference
     * string
     * This is the postscript information visible to the payee.
     */
    private String reference;

    /**
     * additional_info
     * object (Map)
     * Set of key-value pairs that you can attach the business information according to Lianlian's requirements.
     */
    private List<AdditionalInfo> additionalInfo;

    /**
     * create_time
     * long
     * The object creation time. Measured in milliseconds since the Unix epoch. It's a long type number.
     */
    private Date createTime;
}
